#!/usr/bin/env python3
"""
EDR Detector - Detection rule constants.
All rules tagged with MITRE ATT&CK IDs.
"""

# ── Fileless malware patterns (memfd/proc) ────────────────
MEMFD_PATTERNS = [
    "/memfd:",           # memfd_create() 실행
    "/proc/self/fd/",    # /proc/self/fd 통한 실행
    "/proc/*/fd/",       # 다른 프로세스 fd
    "/dev/shm/."         # hidden file in shared memory
]

# ── LOLBins suspicious patterns (LOLBAS-based, 80+ rules) ────
# Each rule: comm patterns, argv regex patterns, name, description, level, mitre
# Level: 3=CRITICAL, 2=WARNING, 1=INFO
# mitre: MITRE ATT&CK Technique ID
LOLBIN_RULES = [
    # === Reverse Shells (T1059 — Command and Scripting Interpreter) ===
    {"comm": ["bash", "sh", "dash", "zsh", "ksh", "csh", "tcsh", "fish"],
     "argv": [r"-i\s+>", r"/dev/tcp/", r"/dev/udp/",
              r"exec\s+\d+<>/dev/tcp", r"0<&\d+-"],
     "name": "shell_reverse", "desc": "쉘 리버스 연결", "level": 3,
     "mitre": "T1059.004"},
    {"comm": ["python", "python3", "python3.*", "python2"],
     "argv": [r"import\s+socket", r"import\s+subprocess",
              r"import\s+pty", r"pty\.spawn", r"exec\(",
              r"eval\(", r"os\.system", r"os\.popen",
              r"__import__", r"compile\("],
     "name": "python_inject", "desc": "Python 코드 인젝션/리버스쉘", "level": 3,
     "mitre": "T1059.006"},
    {"comm": ["nc", "ncat", "netcat", "socat"],
     "argv": [r"-e\s*/bin", r"-e\s*/bin/sh", r"-c\s*/bin",
              r"\|\s*/bin/sh", r"EXEC:", r"TCP:",
              r"exec:'/bin", r"pty,stderr"],
     "name": "netcat_shell", "desc": "Netcat/Socat 쉘 바인드", "level": 3,
     "mitre": "T1059.004"},
    {"comm": ["perl"],
     "argv": [r"socket\(", r"IO::Socket", r"exec\(",
              r"system\(", r"-e\s+'.*socket", r"SOCK_STREAM"],
     "name": "perl_reverse", "desc": "Perl 리버스쉘", "level": 3,
     "mitre": "T1059.006"},
    {"comm": ["ruby"],
     "argv": [r"TCPSocket", r"Socket\.new", r"exec\(",
              r"system\(", r"-rsocket", r"IO\.popen"],
     "name": "ruby_reverse", "desc": "Ruby 리버스쉘", "level": 3,
     "mitre": "T1059.006"},
    {"comm": ["php", "php-cgi", "php-fpm"],
     "argv": [r"fsockopen", r"exec\(", r"system\(",
              r"shell_exec", r"passthru", r"proc_open",
              r"pcntl_exec", r"\$_GET", r"\$_POST"],
     "name": "php_inject", "desc": "PHP 코드 실행/웹쉘", "level": 3,
     "mitre": "T1059.006"},
    {"comm": ["node", "nodejs"],
     "argv": [r"child_process", r"require.*net", r"exec\(",
              r"spawn\(", r"\.connect\("],
     "name": "node_inject", "desc": "Node.js 코드 실행", "level": 3,
     "mitre": "T1059.007"},
    {"comm": ["lua", "luajit"],
     "argv": [r"os\.execute", r"io\.popen", r"socket"],
     "name": "lua_inject", "desc": "Lua 코드 실행", "level": 3,
     "mitre": "T1059"},
    {"comm": ["awk", "gawk", "mawk"],
     "argv": [r"/inet/tcp", r"system\("],
     "name": "awk_reverse", "desc": "AWK 네트워크 연결", "level": 3,
     "mitre": "T1059"},

    # === Download & Execute (T1105 — Ingress Tool Transfer) ===
    {"comm": ["curl"],
     "argv": [r"\|\s*(ba)?sh", r"\|\s*python", r"\|\s*perl",
              r"-o\s*/tmp/", r"-o\s*/dev/shm/", r"-o\s*/var/tmp/",
              r"--output\s*/tmp", r"-O\s+.*\|\s*sh"],
     "name": "curl_exec", "desc": "curl 다운로드+실행", "level": 3,
     "mitre": "T1105"},
    {"comm": ["wget"],
     "argv": [r"\|\s*(ba)?sh", r"\|\s*python", r"-O\s*/tmp/",
              r"-O\s*/dev/shm/", r"-O\s+- \|", r"--output-document=/tmp"],
     "name": "wget_exec", "desc": "wget 다운로드+실행", "level": 3,
     "mitre": "T1105"},
    {"comm": ["tftp"],
     "argv": [r"get\s+", r"put\s+"],
     "name": "tftp_transfer", "desc": "TFTP 파일 전송", "level": 2,
     "mitre": "T1105"},
    {"comm": ["scp"],
     "argv": [r".*@.*:/tmp/", r".*@.*:/dev/shm/"],
     "name": "scp_suspicious", "desc": "SCP 의심 전송", "level": 2,
     "mitre": "T1105"},
    {"comm": ["ftp"],
     "argv": [r"-n\s+", r"anonymous"],
     "name": "ftp_anonymous", "desc": "FTP 익명 연결", "level": 2,
     "mitre": "T1071.002"},

    # === Encoded Payload (T1140 — Deobfuscate/Decode) ===
    {"comm": ["base64"],
     "argv": [r"\|\s*(ba)?sh", r"\|\s*python", r"-d\s+\|"],
     "name": "base64_exec", "desc": "Base64 디코드+실행", "level": 3,
     "mitre": "T1140"},
    {"comm": ["openssl"],
     "argv": [r"enc\s+.*\|\s*sh", r"enc\s+.*\|\s*bash",
              r"s_client", r"s_server"],
     "name": "openssl_abuse", "desc": "OpenSSL 남용", "level": 2,
     "mitre": "T1573.002"},
    {"comm": ["xxd", "od"],
     "argv": [r"-r\s+.*\|\s*sh", r"-r.*\|.*bash"],
     "name": "hex_decode_exec", "desc": "헥스 디코드+실행", "level": 2,
     "mitre": "T1140"},

    # === Privilege Escalation (T1548) ===
    {"comm": ["chmod"],
     "argv": [r"\+s\s+", r"4755\s+", r"u\+s", r"777\s+/tmp/",
              r"\+x\s+/tmp/", r"\+x\s+/dev/shm/"],
     "name": "chmod_suid", "desc": "SUID/권한 변경", "level": 3,
     "mitre": "T1548.001"},
    {"comm": ["chown"],
     "argv": [r"root:\s+", r"root:root", r"0:0"],
     "name": "chown_root", "desc": "root 소유권 변경", "level": 2,
     "mitre": "T1222.002"},
    {"comm": ["pkexec", "doas"],
     "argv": [r"."],
     "name": "pkexec_use", "desc": "권한 상승 도구 사용", "level": 1,
     "mitre": "T1548.003"},
    {"comm": ["find"],
     "argv": [r"-exec\s+/bin", r"-exec\s+sh", r"-perm\s+-4000",
              r"-perm\s+/u=s"],
     "name": "find_suid_exec", "desc": "find SUID 탐색/실행", "level": 2,
     "mitre": "T1548.001"},

    # === Persistence (T1053/T1543) ===
    {"comm": ["crontab"],
     "argv": [r"-e", r"-l", r"-r"],
     "name": "crontab_edit", "desc": "크론탭 수정", "level": 1,
     "mitre": "T1053.003"},
    {"comm": ["at"],
     "argv": [r"."],
     "name": "at_schedule", "desc": "at 작업 등록", "level": 1,
     "mitre": "T1053.002"},
    {"comm": ["systemctl"],
     "argv": [r"enable\s+", r"daemon-reload", r"edit\s+"],
     "name": "systemctl_persist", "desc": "서비스 등록/변경", "level": 2,
     "mitre": "T1543.002"},
    {"comm": ["sed", "tee"],
     "argv": [r"/etc/cron", r"/etc/systemd", r"\.bashrc",
              r"\.profile", r"/etc/rc\.local"],
     "name": "persist_config", "desc": "시작 파일 수정", "level": 2,
     "mitre": "T1546.004"},

    # === Reconnaissance (T1046/T1082) ===
    {"comm": ["nmap"],
     "argv": [r"."],
     "name": "nmap_scan", "desc": "Nmap 스캔", "level": 2,
     "mitre": "T1046"},
    {"comm": ["masscan"],
     "argv": [r"."],
     "name": "masscan", "desc": "Masscan 스캔", "level": 3,
     "mitre": "T1046"},
    {"comm": ["tcpdump"],
     "argv": [r"-w\s+", r"-i\s+"],
     "name": "tcpdump_capture", "desc": "패킷 캡처", "level": 2,
     "mitre": "T1040"},
    {"comm": ["tshark", "wireshark"],
     "argv": [r"."],
     "name": "wireshark", "desc": "패킷 분석 도구", "level": 2,
     "mitre": "T1040"},
    {"comm": ["id", "whoami"],
     "argv": [r"."],
     "name": "user_enum", "desc": "사용자 정보 확인", "level": 1,
     "mitre": "T1033"},

    # === Data Exfiltration (T1560/T1041) ===
    {"comm": ["tar", "zip", "gzip", "bzip2", "xz"],
     "argv": [r"/etc/shadow", r"/etc/passwd", r"\.ssh/",
              r"/root/", r"/home/.*\.ssh"],
     "name": "archive_sensitive", "desc": "민감 파일 압축", "level": 3,
     "mitre": "T1560.001"},
    {"comm": ["dd"],
     "argv": [r"if=/dev/sd", r"if=/dev/nvme", r"of=.*\.",
              r"if=/etc/shadow"],
     "name": "dd_exfil", "desc": "dd 디스크/파일 복사", "level": 3,
     "mitre": "T1005"},
    {"comm": ["cat", "head", "tail", "less", "more"],
     "argv": [r"/etc/shadow", r"/etc/gshadow", r"\.ssh/id_"],
     "name": "read_sensitive", "desc": "민감 파일 읽기", "level": 2,
     "mitre": "T1003.008"},

    # === Evasion (T1070) ===
    {"comm": ["unset"],
     "argv": [r"HISTFILE", r"HISTSIZE", r"HISTFILESIZE"],
     "name": "history_clear", "desc": "쉘 히스토리 삭제", "level": 3,
     "mitre": "T1070.003"},
    {"comm": ["history"],
     "argv": [r"-c", r"-d"],
     "name": "history_delete", "desc": "히스토리 삭제", "level": 3,
     "mitre": "T1070.003"},
    {"comm": ["rm", "shred"],
     "argv": [r"/var/log/", r"\.bash_history", r"/tmp/\.\.",
              r"wtmp", r"btmp", r"lastlog", r"auth\.log"],
     "name": "log_destroy", "desc": "로그 파일 삭제", "level": 3,
     "mitre": "T1070.004"},
    {"comm": ["iptables", "nftables", "ufw"],
     "argv": [r"-F", r"--flush", r"delete", r"disable"],
     "name": "firewall_disable", "desc": "방화벽 해제", "level": 3,
     "mitre": "T1562.004"},
    {"comm": ["setenforce"],
     "argv": [r"0", r"Permissive"],
     "name": "selinux_disable", "desc": "SELinux 비활성화", "level": 3,
     "mitre": "T1562.001"},
    {"comm": ["apparmor_parser"],
     "argv": [r"-R", r"--remove"],
     "name": "apparmor_disable", "desc": "AppArmor 제거", "level": 3,
     "mitre": "T1562.001"},

    # === Cryptominer (T1496) ===
    {"comm": ["xmrig", "minerd", "cpuminer", "cgminer", "bfgminer",
              "ethminer", "t-rex", "phoenixminer", "nbminer"],
     "argv": [r"."],
     "name": "cryptominer", "desc": "암호화폐 마이너", "level": 3,
     "mitre": "T1496"},
    {"comm": ["*"],
     "argv": [r"stratum\+tcp://", r"stratum\+ssl://",
              r"--donate-level", r"-o\s+pool\."],
     "name": "mining_args", "desc": "마이닝 인자 감지", "level": 3,
     "mitre": "T1496"},

    # ── 컴파일러/인터프리터 남용 (T1027.004) ──────────────
    {"comm": ["gcc", "g++", "cc"],
     "argv": [r"-o\s+/tmp/", r"-o\s+/dev/shm/", r"-o\s+\.\./",
              r"-x\s+c\s+-", r"-pipe"],
     "name": "compiler_abuse", "desc": "컴파일러로 악성 바이너리 생성", "level": 3,
     "mitre": "T1027.004"},
    {"comm": ["make", "cmake"],
     "argv": [r"-C\s+/tmp/", r"-C\s+/dev/shm/", r"--directory=/tmp"],
     "name": "build_abuse", "desc": "빌드 도구 남용", "level": 2,
     "mitre": "T1027.004"},
    {"comm": ["go"],
     "argv": [r"run\s+.*\.go", r"build\s+-o\s+/tmp/"],
     "name": "go_run", "desc": "Go 코드 즉시 실행", "level": 2,
     "mitre": "T1059"},
    {"comm": ["rustc"],
     "argv": [r"-o\s+/tmp/", r"-o\s+/dev/shm/"],
     "name": "rust_compile", "desc": "Rust 컴파일+실행", "level": 2,
     "mitre": "T1027.004"},
    {"comm": ["dotnet"],
     "argv": [r"run", r"exec", r"script"],
     "name": "dotnet_exec", "desc": ".NET 코드 실행", "level": 2,
     "mitre": "T1059"},
    {"comm": ["javac"],
     "argv": [r"-d\s+/tmp/", r".*\.java"],
     "name": "java_compile", "desc": "Java 컴파일", "level": 1,
     "mitre": "T1059"},
    {"comm": ["java"],
     "argv": [r"-jar\s+/tmp/", r"-jar\s+/dev/shm/", r"-cp\s+/tmp/"],
     "name": "java_run_tmp", "desc": "임시 경로에서 JAR 실행", "level": 3,
     "mitre": "T1059"},
    {"comm": ["as", "ld"],
     "argv": [r"-o\s+/tmp/", r"-o\s+/dev/shm/"],
     "name": "assembler_abuse", "desc": "어셈블러/링커 직접 사용", "level": 3,
     "mitre": "T1027.004"},
    {"comm": ["mono", "csc"],
     "argv": [r"/tmp/", r"/dev/shm/"],
     "name": "mono_abuse", "desc": "Mono/.NET 임시 실행", "level": 2,
     "mitre": "T1059"},
    {"comm": ["tcc"],
     "argv": [r"-run", r"-"],
     "name": "tcc_run", "desc": "TCC 즉시 컴파일+실행", "level": 3,
     "mitre": "T1027.004"},

    # ── 파일시스템 조작 (T1006/T1561) ─────────────────────
    {"comm": ["mount"],
     "argv": [r"-o\s+bind", r"-t\s+overlay", r"-t\s+nfs",
              r"--bind", r"-o\s+remount"],
     "name": "mount_abuse", "desc": "파일시스템 마운트 조작", "level": 3,
     "mitre": "T1006"},
    {"comm": ["umount"],
     "argv": [r"-l\s+/", r"--lazy"],
     "name": "lazy_umount", "desc": "파일시스템 지연 언마운트", "level": 2,
     "mitre": "T1006"},
    {"comm": ["losetup"],
     "argv": [r"--find", r"-f"],
     "name": "loop_device", "desc": "루프 디바이스 생성", "level": 2,
     "mitre": "T1006"},
    {"comm": ["mkfs", "mkfs.ext4", "mkfs.xfs"],
     "argv": [r"/dev/sd", r"/dev/nvme", r"/dev/loop"],
     "name": "mkfs_dangerous", "desc": "파일시스템 생성 (데이터 파괴 위험)", "level": 3,
     "mitre": "T1561.002"},
    {"comm": ["debugfs"],
     "argv": [r"-w", r"-R"],
     "name": "debugfs_write", "desc": "ext 파일시스템 직접 조작", "level": 3,
     "mitre": "T1006"},
    {"comm": ["hdparm"],
     "argv": [r"--security-erase", r"--dco-restore"],
     "name": "hdparm_erase", "desc": "디스크 보안 삭제", "level": 3,
     "mitre": "T1561.001"},
    {"comm": ["blkdiscard"],
     "argv": [r"/dev/"],
     "name": "blk_discard", "desc": "블록 삭제 (데이터 파괴)", "level": 3,
     "mitre": "T1561.001"},
    {"comm": ["dd"],
     "argv": [r"of=/dev/sd", r"of=/dev/nvme", r"if=/dev/zero\s+of=/dev/",
              r"if=/dev/urandom\s+of=/dev/"],
     "name": "dd_device_wipe", "desc": "dd 디바이스 덮어쓰기", "level": 3,
     "mitre": "T1561.001"},
    {"comm": ["shred"],
     "argv": [r"-u", r"--remove", r"/etc/", r"/var/log/"],
     "name": "shred_files", "desc": "파일 안전 삭제", "level": 3,
     "mitre": "T1070.004"},
    {"comm": ["wipefs"],
     "argv": [r"-a", r"--all"],
     "name": "wipefs_all", "desc": "파일시스템 시그니처 전체 삭제", "level": 3,
     "mitre": "T1561.002"},

    # ── 네트워크 도구 (T1572/T1090) ───────────────────────
    {"comm": ["ssh"],
     "argv": [r"-L\s+", r"-R\s+", r"-D\s+", r"-w\s+",
              r"-o\s+ProxyCommand", r"-J\s+"],
     "name": "ssh_tunnel", "desc": "SSH 터널/포워딩", "level": 2,
     "mitre": "T1572"},
    {"comm": ["ssh"],
     "argv": [r"-o\s+StrictHostKeyChecking=no",
              r"-o\s+UserKnownHostsFile=/dev/null"],
     "name": "ssh_no_verify", "desc": "SSH 호스트키 검증 비활성화", "level": 2,
     "mitre": "T1021.004"},
    {"comm": ["openconnect", "openvpn"],
     "argv": [r"--config", r"--auth", r".*"],
     "name": "vpn_tunnel", "desc": "VPN 터널 생성", "level": 2,
     "mitre": "T1572"},
    {"comm": ["stunnel", "stunnel4"],
     "argv": [r".*"],
     "name": "ssl_tunnel", "desc": "SSL 래핑 터널", "level": 2,
     "mitre": "T1573.002"},
    {"comm": ["proxychains", "proxychains4"],
     "argv": [r".*"],
     "name": "proxy_chain", "desc": "프록시 체인 사용", "level": 3,
     "mitre": "T1090.003"},
    {"comm": ["iodine", "iodined"],
     "argv": [r".*"],
     "name": "dns_tunnel", "desc": "DNS 터널링 (iodine)", "level": 3,
     "mitre": "T1572"},
    {"comm": ["chisel"],
     "argv": [r"client", r"server"],
     "name": "chisel_tunnel", "desc": "Chisel 리버스 터널", "level": 3,
     "mitre": "T1572"},
    {"comm": ["ligolo", "ligolo-ng"],
     "argv": [r".*"],
     "name": "ligolo_tunnel", "desc": "Ligolo 리버스 터널", "level": 3,
     "mitre": "T1572"},
    {"comm": ["redsocks"],
     "argv": [r".*"],
     "name": "transparent_proxy", "desc": "투명 프록시", "level": 3,
     "mitre": "T1090"},
    {"comm": ["nmap"],
     "argv": [r"-sS", r"-sV", r"-sC", r"-O", r"-A",
              r"--script", r"-p-", r"10\.", r"192\.168\.", r"172\."],
     "name": "nmap_scan", "desc": "Nmap 스캔", "level": 2,
     "mitre": "T1046"},
    {"comm": ["masscan"],
     "argv": [r"--rate", r"-p", r"--banners"],
     "name": "masscan", "desc": "Masscan 대량 스캔", "level": 3,
     "mitre": "T1046"},
    {"comm": ["tcpdump"],
     "argv": [r"-w\s+/tmp/", r"-w\s+/dev/shm/", r"-nn"],
     "name": "tcpdump_capture", "desc": "패킷 캡처 (정찰)", "level": 2,
     "mitre": "T1040"},
    {"comm": ["tshark"],
     "argv": [r"-w\s+", r"--export-objects"],
     "name": "tshark_capture", "desc": "Wireshark 캡처", "level": 2,
     "mitre": "T1040"},
    {"comm": ["hping3"],
     "argv": [r"--flood", r"--syn", r"-S"],
     "name": "hping_flood", "desc": "hping3 DoS/스캔", "level": 3,
     "mitre": "T1498"},
    {"comm": ["netcat", "ncat"],
     "argv": [r"-e", r"--exec", r"-c", r"--sh-exec"],
     "name": "netcat_exec", "desc": "Netcat 명령 실행", "level": 3,
     "mitre": "T1059.004"},

    # ── 디버거/분석 도구 남용 (T1055/T1027) ───────────────
    {"comm": ["gdb"],
     "argv": [r"-batch", r"-ex\s+.*call\s+system",
              r"-ex\s+.*shell", r"--pid="],
     "name": "gdb_exec", "desc": "GDB 코드 인젝션", "level": 3,
     "mitre": "T1055.008"},
    {"comm": ["ltrace"],
     "argv": [r"-p\s+", r"-e\s+"],
     "name": "ltrace_spy", "desc": "ltrace 라이브러리 감시", "level": 1,
     "mitre": "T1057"},
    {"comm": ["objcopy"],
     "argv": [r"--add-section", r"--set-section-flags",
              r"--change-section-address"],
     "name": "objcopy_inject", "desc": "바이너리 섹션 조작", "level": 3,
     "mitre": "T1027.009"},
    {"comm": ["strip"],
     "argv": [r"--strip-all", r"-s"],
     "name": "strip_binary", "desc": "바이너리 심볼 제거 (은닉)", "level": 2,
     "mitre": "T1027.007"},
    {"comm": ["readelf", "nm"],
     "argv": [r"-s", r"--symbols", r"-D"],
     "name": "binary_recon", "desc": "바이너리 분석 (정찰)", "level": 1,
     "mitre": "T1005"},
    {"comm": ["perf"],
     "argv": [r"record", r"probe", r"trace"],
     "name": "perf_trace", "desc": "성능 모니터 (시스템 정찰)", "level": 1,
     "mitre": "T1082"},
    {"comm": ["LD_PRELOAD"],
     "argv": [r".*"],
     "name": "ld_preload", "desc": "LD_PRELOAD 라이브러리 주입", "level": 3,
     "mitre": "T1574.006"},
    {"comm": ["patchelf"],
     "argv": [r"--set-interpreter", r"--set-rpath", r"--add-needed"],
     "name": "patchelf_modify", "desc": "ELF 바이너리 수정", "level": 3,
     "mitre": "T1574.006"},
    {"comm": ["chrpath"],
     "argv": [r"-r", r"--replace"],
     "name": "chrpath_modify", "desc": "RPATH 변경", "level": 2,
     "mitre": "T1574.006"},
    {"comm": ["execstack"],
     "argv": [r"-s", r"--set-execstack"],
     "name": "execstack_set", "desc": "실행 스택 활성화 (DEP 우회)", "level": 3,
     "mitre": "T1055"},

    # ── 사용자/그룹 조작 (T1136/T1098) ────────────────────
    {"comm": ["useradd", "adduser"],
     "argv": [r"-o", r"--non-unique", r"-u\s+0",
              r"-G\s+sudo", r"-G\s+wheel", r"-G\s+root"],
     "name": "user_create_priv", "desc": "특권 사용자 생성", "level": 3,
     "mitre": "T1136.001"},
    {"comm": ["useradd", "adduser"],
     "argv": [r".*"],
     "name": "user_create", "desc": "사용자 추가", "level": 2,
     "mitre": "T1136.001"},
    {"comm": ["usermod"],
     "argv": [r"-aG\s+sudo", r"-aG\s+wheel", r"-aG\s+root",
              r"-aG\s+docker", r"-u\s+0", r"-o"],
     "name": "user_privesc", "desc": "사용자 권한 상승", "level": 3,
     "mitre": "T1098"},
    {"comm": ["passwd"],
     "argv": [r"--stdin", r"-d", r"--delete"],
     "name": "passwd_modify", "desc": "패스워드 변경/삭제", "level": 2,
     "mitre": "T1098"},
    {"comm": ["chpasswd"],
     "argv": [r".*"],
     "name": "bulk_passwd", "desc": "대량 패스워드 변경", "level": 3,
     "mitre": "T1098"},
    {"comm": ["visudo"],
     "argv": [r".*"],
     "name": "sudoers_edit", "desc": "sudoers 편집", "level": 3,
     "mitre": "T1548.003"},
    {"comm": ["groupadd"],
     "argv": [r".*"],
     "name": "group_create", "desc": "그룹 생성", "level": 1,
     "mitre": "T1136.001"},
    {"comm": ["userdel", "deluser"],
     "argv": [r"--remove", r"-r"],
     "name": "user_delete", "desc": "사용자 삭제", "level": 2,
     "mitre": "T1531"},
    {"comm": ["chsh"],
     "argv": [r"-s\s+/bin/bash", r"-s\s+/bin/sh"],
     "name": "shell_change", "desc": "로그인 쉘 변경", "level": 1,
     "mitre": "T1098"},
    {"comm": ["pkexec"],
     "argv": [r".*"],
     "name": "pkexec_priv", "desc": "pkexec 권한 상승", "level": 2,
     "mitre": "T1548.003"},

    # ── 로그/감사 우회 (T1070/T1562) ──────────────────────
    {"comm": ["auditctl"],
     "argv": [r"-D", r"--delete", r"-W\s+"],
     "name": "audit_disable", "desc": "감사 규칙 삭제", "level": 3,
     "mitre": "T1562.001"},
    {"comm": ["systemctl"],
     "argv": [r"stop\s+rsyslog", r"stop\s+auditd",
              r"stop\s+syslog", r"disable\s+auditd",
              r"mask\s+rsyslog", r"stop\s+journald"],
     "name": "log_service_stop", "desc": "로그 서비스 중지", "level": 3,
     "mitre": "T1562.001"},
    {"comm": ["journalctl"],
     "argv": [r"--vacuum-size=", r"--vacuum-time=",
              r"--rotate", r"--flush"],
     "name": "journal_vacuum", "desc": "저널 로그 축소/삭제", "level": 3,
     "mitre": "T1070.003"},
    {"comm": ["logrotate"],
     "argv": [r"-f", r"--force"],
     "name": "logrotate_force", "desc": "강제 로그 로테이션", "level": 2,
     "mitre": "T1070.003"},
    {"comm": ["truncate"],
     "argv": [r"-s\s+0", r"--size=0", r"/var/log/"],
     "name": "truncate_logs", "desc": "로그 파일 비우기", "level": 3,
     "mitre": "T1070.003"},
    {"comm": ["bash", "sh", "zsh"],
     "argv": [r"echo\s*>\s*\.bash_history",
              r"history\s+-c", r"set\s+\+o\s+history",
              r"unset\s+HISTFILE", r"HISTSIZE=0"],
     "name": "history_clear", "desc": "쉘 히스토리 삭제/비활성화", "level": 3,
     "mitre": "T1070.003"},
    {"comm": ["touch"],
     "argv": [r"-t\s+", r"-d\s+", r"--date=",
              r"-r\s+/usr/bin/"],
     "name": "timestamp_tamper", "desc": "파일 타임스탬프 조작", "level": 2,
     "mitre": "T1070.006"},
    {"comm": ["timedatectl"],
     "argv": [r"set-time", r"set-ntp\s+false"],
     "name": "time_tamper", "desc": "시스템 시간 변경", "level": 3,
     "mitre": "T1070.006"},
    {"comm": ["rm"],
     "argv": [r"-rf\s+/var/log/", r"/var/log/syslog",
              r"/var/log/auth\.log", r"/var/log/kern\.log"],
     "name": "log_delete", "desc": "로그 파일 삭제", "level": 3,
     "mitre": "T1070.004"},
    {"comm": ["sed", "awk"],
     "argv": [r"-i.*/var/log/", r"/var/log/.*\{.*d\}"],
     "name": "log_edit", "desc": "로그 파일 인라인 편집", "level": 3,
     "mitre": "T1070.004"},

    # ── 커널/부트 조작 (T1014/T1542) ──────────────────────
    {"comm": ["insmod"],
     "argv": [r".*\.ko"],
     "name": "kernel_module_load", "desc": "커널 모듈 직접 로드", "level": 3,
     "mitre": "T1547.006"},
    {"comm": ["modprobe"],
     "argv": [r"--force", r"-f"],
     "name": "modprobe_force", "desc": "커널 모듈 강제 로드", "level": 3,
     "mitre": "T1547.006"},
    {"comm": ["kexec"],
     "argv": [r"-l", r"--load", r"-e", r"--exec"],
     "name": "kexec_load", "desc": "커널 재로드 (부트 우회)", "level": 3,
     "mitre": "T1542"},
    {"comm": ["grub-install", "update-grub"],
     "argv": [r".*"],
     "name": "bootloader_modify", "desc": "부트로더 변경", "level": 3,
     "mitre": "T1542.003"},
    {"comm": ["update-initramfs", "mkinitramfs", "dracut"],
     "argv": [r"-u", r"-c", r"--force"],
     "name": "initrd_modify", "desc": "initrd/initramfs 수정", "level": 3,
     "mitre": "T1542"},

    # ── 데이터 유출 확장 (T1048/T1567) ────────────────────
    {"comm": ["dig", "nslookup", "host"],
     "argv": [r"TXT\s+.*\.", r"-t\s+TXT"],
     "name": "dns_exfil", "desc": "DNS TXT 레코드 유출", "level": 2,
     "mitre": "T1048.003"},
    {"comm": ["aws"],
     "argv": [r"s3\s+cp", r"s3\s+sync", r"s3\s+mv"],
     "name": "aws_s3_upload", "desc": "AWS S3 업로드", "level": 2,
     "mitre": "T1567.002"},
    {"comm": ["gsutil"],
     "argv": [r"cp", r"rsync", r"mv"],
     "name": "gcs_upload", "desc": "Google Cloud Storage 업로드", "level": 2,
     "mitre": "T1567.002"},
    {"comm": ["az"],
     "argv": [r"storage\s+blob\s+upload"],
     "name": "azure_upload", "desc": "Azure Storage 업로드", "level": 2,
     "mitre": "T1567.002"},
    {"comm": ["smbclient"],
     "argv": [r"-c\s+.*put", r"--command=.*put"],
     "name": "smb_upload", "desc": "SMB 공유 업로드", "level": 2,
     "mitre": "T1021.002"},
    {"comm": ["ftp", "lftp"],
     "argv": [r"put\s+", r"mput\s+", r"-e.*open.*put"],
     "name": "ftp_upload", "desc": "FTP 업로드", "level": 2,
     "mitre": "T1048.003"},
    {"comm": ["git"],
     "argv": [r"push", r"remote\s+add"],
     "name": "git_exfil", "desc": "Git push (코드 유출)", "level": 1,
     "mitre": "T1567"},
    {"comm": ["rsync"],
     "argv": [r"--rsh=ssh", r"-e\s+ssh", r".*@.*:"],
     "name": "rsync_remote", "desc": "원격 rsync 전송", "level": 1,
     "mitre": "T1048"},
    {"comm": ["steghide"],
     "argv": [r"embed", r"--coverfile"],
     "name": "steganography", "desc": "스테가노그래피 숨김", "level": 3,
     "mitre": "T1027.003"},
    {"comm": ["xclip", "xsel", "wl-copy"],
     "argv": [r"-selection\s+clipboard", r"--clipboard"],
     "name": "clipboard_exfil", "desc": "클립보드 유출", "level": 2,
     "mitre": "T1115"},
]

# ── Behavioral sequence patterns ──────────────────────────
SEQUENCE_PATTERNS = [
    {
        "name": "dropper",
        "description": "파일 다운로드 후 실행 (드롭퍼 의심)",
        "mitre": "T1204.002",
        "steps": [
            {"type": 1, "path_match": "/tmp/*"},
            {"type": 3},
        ],
        "window_secs": 30,
        "alert_level": 3,
    },
    {
        "name": "reverse_shell",
        "description": "프로세스 실행 후 즉시 외부 연결 (리버스 셸 의심)",
        "mitre": "T1059.004",
        "steps": [
            {"type": 1, "path_match": "/tmp/*|/dev/shm/*|/var/tmp/*"},
            {"type": 3},
        ],
        "window_secs": 5,
        "alert_level": 3,
    },
    {
        "name": "priv_exec",
        "description": "권한 상승 후 프로세스 실행",
        "mitre": "T1548",
        "steps": [
            {"type": 5},
            {"type": 1},
        ],
        "window_secs": 10,
        "alert_level": 3,
    },
]
